"""
fetch_leqp_members.py
Henter alle aktive ryttere fra L'Equipe Provence (ZwiftPower team 2003)
og gemmer dem i data/leqp_members.js til brug i Rider Intel.

Kør manuelt eller som del af full_update.
Kræver at API'en kører på http://127.0.0.1:8000

Usage:
    python fetch_leqp_members.py
"""

import requests
import json
import os

TEAM_ID  = 2003
MAX_RANK = 599
API_URL  = "http://127.0.0.1:8000"
OUT_FILE = os.path.join(os.path.dirname(__file__), "data", "leqp_members.js")


def main():
    print(f"Henter aktive ryttere fra LEQP (team {TEAM_ID}, rank <= {MAX_RANK})...")

    try:
        r = requests.get(f"{API_URL}/team/{TEAM_ID}?max_rank={MAX_RANK}", timeout=60)
        r.raise_for_status()
        members = r.json()
    except Exception as e:
        print(f"FEJL: {e}")
        return

    print(f"Fandt {len(members)} aktive ryttere")

    def fmt(val):
        if val is None:
            return 'null'
        if isinstance(val, float) and val == int(val):
            return str(int(val))
        return str(val)

    js_entries = []
    for m in members:
        name = m["name"].replace("'", "\\'")
        js_entries.append(
            f'  {{ zwift_id: {m["zwift_id"]}, name: \'{name}\', rank: {m["rank"]}'
            f', h_15_wkg: {fmt(m.get("h_15_wkg"))}, h_15_watts: {fmt(m.get("h_15_watts"))}'
            f', h_1200_wkg: {fmt(m.get("h_1200_wkg"))}, h_1200_watts: {fmt(m.get("h_1200_watts"))}'
            f', skill_race: {fmt(m.get("skill_race"))}, skill_seg: {fmt(m.get("skill_seg"))}, skill_power: {fmt(m.get("skill_power"))}'
            f', distance: {fmt(m.get("distance"))}, climbed: {fmt(m.get("climbed"))} }}'
        )

    content = (
        "// LEQP_MEMBERS_START\n"
        "// Auto-generated by fetch_leqp_members.py — do not edit manually\n"
        f"// {len(members)} aktive ryttere (rank 1-{MAX_RANK}) fra L'Equipe Provence (ZwiftPower team {TEAM_ID})\n"
        "const LEQP_MEMBERS = [\n"
        + ",\n".join(js_entries) + "\n"
        "];\n"
        "// LEQP_MEMBERS_END\n"
    )

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Gemt: {OUT_FILE}")


if __name__ == "__main__":
    main()
