"""
lookup_routes.py
Builds/updates data/routes.js by extracting ZP_ROUTES from a ZwiftPower event page.
All Zwift route IDs and names are embedded in every event page as a JS lookup table.

Usage: python lookup_routes.py
"""

import asyncio
import json
import os
import re
import sys

ROUTES_JS = os.path.join(os.path.dirname(__file__), "data", "routes.js")

# ── Load existing routes database ─────────────────────────────────────────────

def load_routes_db() -> dict:
    """Returns {rt_id_str: route_name} from data/routes.js"""
    if not os.path.exists(ROUTES_JS):
        return {}
    with open(ROUTES_JS, encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'const ROUTES\s*=\s*(\{.*?\});', content, re.DOTALL)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except Exception:
        return {}

# ── Save routes.js ─────────────────────────────────────────────────────────────

def save_routes_db(db: dict):
    # Filter out empty entries before saving
    clean = {k: v for k, v in db.items() if v}
    content = "// Zwift route ID → route name (auto-generated by lookup_routes.py)\n"
    content += "// Do not edit manually — run lookup_routes.py to update\n"
    content += "const ROUTES = " + json.dumps(clean, ensure_ascii=False, indent=2) + ";\n"
    with open(ROUTES_JS, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Gemt {len(clean)} ruter til data/routes.js")

# ── Fetch ZP_ROUTES from ZwiftPower event page ─────────────────────────────────

async def fetch_zp_routes(username: str, password: str) -> dict:
    """Fetches the full ZP_ROUTES table from a single ZwiftPower event page."""
    from zpdatafetch.zp import ZP
    from zpdatafetch.async_zp import AsyncZP

    zp = ZP(skip_credential_check=True)
    zp.username = username
    zp.password = password
    zp.login()

    async_zp = AsyncZP(skip_credential_check=True)
    await async_zp.init_client()
    async_zp._client.cookies = zp._client.cookies

    # Any event page works — use a recent LEQP ladder event
    url = "https://zwiftpower.com/events.php?zid=5513506"
    resp = await async_zp._client.get(url)
    text = resp.text

    routes = {}
    for m in re.finditer(r'ZP_ROUTES\[(\d+)\]\s*=\s*\{name:"([^"]+)"', text):
        routes[m.group(1)] = m.group(2)

    return routes

# ── Main ───────────────────────────────────────────────────────────────────────

async def main():
    username = os.getenv("ZWIFTPOWER_USERNAME", "")
    password = os.getenv("ZWIFTPOWER_PASSWORD", "")
    if not username or not password:
        print("FEJL: Sæt ZWIFTPOWER_USERNAME og ZWIFTPOWER_PASSWORD som miljøvariabler")
        sys.exit(1)

    existing = load_routes_db()
    print(f"Eksisterende database: {len(existing)} ruter")

    print("Henter ZP_ROUTES fra ZwiftPower...")
    zp_routes = await fetch_zp_routes(username, password)
    print(f"Fandt {len(zp_routes)} ruter fra ZwiftPower")

    if not zp_routes:
        print("FEJL: Ingen ruter hentet — tjek login")
        sys.exit(1)

    # Merge: ZwiftPower is authoritative (names may be updated)
    merged = {**existing, **zp_routes}
    new_count = sum(1 for k in zp_routes if not existing.get(k))
    updated_count = sum(1 for k in zp_routes if existing.get(k) and existing[k] != zp_routes[k])

    save_routes_db(merged)
    print(f"Færdig: {new_count} nye ruter, {updated_count} opdaterede navne.")

if __name__ == "__main__":
    asyncio.run(main())
