"""
lookup_routes.py
Looks up Zwift route names for unknown rt-IDs via ZwiftPower event results.
Run once to build the database, then incrementally on each full_update.

Usage: python lookup_routes.py
"""

import asyncio
import json
import os
import re
import sys
import time

ROUTES_JS = os.path.join(os.path.dirname(__file__), "data", "routes.js")
DATA_DIR   = os.path.join(os.path.dirname(__file__), "data")

# ── Load existing routes database ─────────────────────────────────────────────

def load_routes_db() -> dict:
    """Returns {rt_id_str: route_name} from data/routes.js"""
    if not os.path.exists(ROUTES_JS):
        return {}
    with open(ROUTES_JS, encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'const ROUTES\s*=\s*(\{.*?\});', content, re.DOTALL)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except Exception:
        return {}

# ── Collect all rt + zid pairs from data files ────────────────────────────────

def collect_rt_zid_pairs() -> dict:
    """Returns {rt_str: zid_str} — one representative zid per rt."""
    pairs = {}
    for fname in ("ladder_races.js", "other_races.js", "rides.js"):
        path = os.path.join(DATA_DIR, fname)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            content = f.read()
        # Find all {"zid": "...", "rt": "...", ...} patterns
        for m in re.finditer(r'"zid"\s*:\s*"?(\d+)"?.*?"rt"\s*:\s*"?(\d+)"?', content):
            zid, rt = m.group(1), m.group(2)
            if rt and rt not in pairs:
                pairs[rt] = zid
        # Also try reversed order: rt before zid
        for m in re.finditer(r'"rt"\s*:\s*"?(\d+)"?.*?"zid"\s*:\s*"?(\d+)"?', content):
            rt, zid = m.group(1), m.group(2)
            if rt and rt not in pairs:
                pairs[rt] = zid
    return pairs

# ── Fetch route name from ZwiftPower ──────────────────────────────────────────

async def fetch_route_name(zid: str, username: str, password: str) -> str | None:
    """Fetches the route name for a given event zid via ZwiftPower."""
    try:
        from zpdatafetch.zp import ZP
        from zpdatafetch.zpresultfetch import ZPResultFetch

        zp = ZP()
        os.environ["ZPDATAFETCH_USERNAME"] = username
        os.environ["ZPDATAFETCH_PASSWORD"] = password
        zp.login()

        fetcher = ZPResultFetch()
        fetcher.set_zp_session(zp)
        await fetcher.afetch(int(zid))

        result = fetcher._fetched.get(int(zid))
        if result and hasattr(result, "_excluded"):
            route = result._excluded.get("route")
            if route:
                return str(route).strip()
    except Exception as e:
        print(f"  Fejl ved opslag af zid={zid}: {e}")
    return None

# ── Save routes.js ─────────────────────────────────────────────────────────────

def save_routes_db(db: dict):
    content = "// Zwift route ID → route name (auto-generated by lookup_routes.py)\n"
    content += "// Do not edit manually — run lookup_routes.py to update\n"
    content += "const ROUTES = " + json.dumps(db, ensure_ascii=False, indent=2) + ";\n"
    with open(ROUTES_JS, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Gemt {len(db)} ruter til data/routes.js")

# ── Main ───────────────────────────────────────────────────────────────────────

async def main():
    username = os.getenv("ZWIFTPOWER_USERNAME", "")
    password = os.getenv("ZWIFTPOWER_PASSWORD", "")
    if not username or not password:
        print("FEJL: Sæt ZWIFTPOWER_USERNAME og ZWIFTPOWER_PASSWORD som miljøvariabler")
        sys.exit(1)

    db = load_routes_db()
    print(f"Eksisterende database: {len(db)} ruter")

    pairs = collect_rt_zid_pairs()
    print(f"Unikke rt-IDs i data: {len(pairs)}")

    unknown = {rt: zid for rt, zid in pairs.items() if rt not in db}
    print(f"Nye rt-IDs der mangler navn: {len(unknown)}")

    if not unknown:
        print("Ingen nye ruter at slå op — database er opdateret.")
        return

    looked_up = 0
    failed = 0
    for rt, zid in unknown.items():
        print(f"  Slår op: rt={rt} via event zid={zid} ...", end=" ", flush=True)
        name = await fetch_route_name(zid, username, password)
        if name:
            db[rt] = name
            looked_up += 1
            print(f"→ {name}")
        else:
            db[rt] = ""  # Mark as attempted so we don't retry every time
            failed += 1
            print("→ ikke fundet")
        time.sleep(0.5)  # Undgå at ramme rate-limit

    save_routes_db(db)
    print(f"\nFærdig: {looked_up} nye ruter fundet, {failed} ikke fundet.")

if __name__ == "__main__":
    asyncio.run(main())
